!!python/object/new:moveit_msgs.msg._RobotTrajectory.RobotTrajectory {state: [!!python/object/new:trajectory_msgs.msg._JointTrajectory.JointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, world]}, [ur5_shoulder_pan_joint, ur5_shoulder_lift_joint,
          ur5_elbow_joint, ur5_wrist_1_joint, ur5_wrist_2_joint, ur5_wrist_3_joint],
        [!!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [-0.004705188099116242, -2.0390048569924666, -1.4137867776159787,
                -1.2565650146584417, 1.5708486097759335, 0.0015718824729882286], !!python/tuple [
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [0.9269120923289769,
                0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 0]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [7.098033083602786e-05, -2.0389696299185505, -1.4137062253795352,
                -1.2565561403254064, 1.5707076352557654, -4.507641270756722e-05],
              !!python/tuple [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [-0.9269120923289769,
                -0.006836526238365192, -0.015632790827774263, -0.0017222438283795805,
                0.027358957157931775, 0.31380357831417577], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 101516244]}]}]]}, !!python/object/new:trajectory_msgs.msg._MultiDOFJointTrajectory.MultiDOFJointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, '']}, [], []]}]}
